# Advanced NumPy for Data Science

This notebook continues from the NumPy fundamentals and focuses on practical, intermediate-to-advanced patterns used in Data Science workflows.

## 1. Setup and Reproducible Randomness

Use `default_rng()` for modern NumPy random workflows. A fixed seed makes experiments reproducible.

In [2]:
import numpy as np

rng = np.random.default_rng(seed=42)
print("Ready for advanced NumPy")

Ready for advanced NumPy


## 2. Random Data Generation

Random arrays are useful for simulations, experiments, testing, and ML practice.

In [3]:
uniform = rng.random((3, 3))
integers = rng.integers(low=1, high=100, size=(3, 4))
normal = rng.normal(loc=50, scale=10, size=8)
choices = rng.choice(["A", "B", "C"], size=10, replace=True)

print("Uniform random:\n", uniform)
print("Random integers:\n", integers)
print("Normal distribution:", normal)
print("Random choices:", choices)

Uniform random:
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
Random integers:
 [[84 45 50 37]
 [19 92 78 64]
 [40 82 54 44]]
Normal distribution: [41.40707537 53.68750784 40.41117399 58.78450301 49.50074089 48.15137636
 43.19070456 62.22541339]
Random choices: ['B' 'C' 'C' 'C' 'C' 'A' 'B' 'B' 'B' 'A']


## 3. Advanced Boolean Logic

Use `any`, `all`, `where`, and compound masks to build clean conditions.

In [ ]:
scores = np.array([35, 55, 65, 75, 95, 100])

passing_mask = scores >= 60
excellent_mask = scores >= 90
labels = np.where(scores >= 60, "pass", "fail")

print("Any perfect score?", np.any(scores == 100))
print("Did everyone pass?", np.all(passing_mask))
print("Passing scores:", scores[passing_mask])
print("Excellent scores:", scores[excellent_mask])
print("Labels:", labels)

## 4. Conditional Selection with `where`, `select`, and `clip`

These methods are useful for cleaning values, applying business rules, and creating derived features.

In [ ]:
values = np.array([-10, 0, 25, 50, 120])

cleaned = np.where(values < 0, 0, values)
capped = np.clip(values, 0, 100)
conditions = [values < 0, values <= 50, values > 50]
choices = ["invalid", "normal", "high"]
buckets = np.select(conditions, choices, default="unknown")

print("Original:", values)
print("Negative values replaced:", cleaned)
print("Clipped between 0 and 100:", capped)
print("Buckets:", buckets)

## 5. Views vs Copies

Understanding views and copies prevents accidental data changes.

In [ ]:
arr = np.arange(1, 7)
view = arr[1:4]
copy = arr[1:4].copy()

view[0] = 999
copy[1] = 555

print("Original after editing view:", arr)
print("View:", view)
print("Copy:", copy)

## 6. Broadcasting in Real Data

Broadcasting is often used to center or scale features column by column.

In [6]:
data = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000]
])

column_means = data.mean(axis=0)
centered = data - column_means

print("Data:\n", data)
print("Column means:", column_means)
print("Centered data:\n", centered)

Data:
 [[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]]
Column means: [  20.  200. 2000.]
Centered data:
 [[  -10.  -100. -1000.]
 [    0.     0.     0.]
 [   10.   100.  1000.]]


## 7. Standardization

Standardization transforms each feature to have mean 0 and standard deviation 1. This is common before many ML models.

In [7]:
features = np.array([
    [10, 100],
    [20, 120],
    [30, 140],
    [40, 160]
])

mean = features.mean(axis=0)
std = features.std(axis=0)
standardized = (features - mean) / std

print("Mean:", mean)
print("Std:", std)
print("Standardized:\n", standardized)
print("New mean:", standardized.mean(axis=0))
print("New std:", standardized.std(axis=0))

Mean: [ 25. 130.]
Std: [11.18033989 22.36067977]
Standardized:
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
New mean: [0. 0.]
New std: [1. 1.]


## 8. Matrix Multiplication

Use `@` or `np.matmul()` for matrix multiplication. This is core to Machine Learning, linear regression, neural networks, and linear algebra.

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])
vector = np.array([5, 6])

print("A @ B:\n", A @ B)
print("A @ vector:", A @ vector)
print("Element-wise A * B:\n", A * B)

A @ B:
 [[ 70 100]
 [150 220]]
A @ vector: [17 39]
Element-wise A * B:
 [[ 10  40]
 [ 90 160]]


## 9. Linear Algebra Methods

NumPy includes a linear algebra module for determinant, inverse, solving equations, eigenvalues, and norms.

In [ ]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

solution = np.linalg.solve(A, b)
determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
norm = np.linalg.norm(b)

print("Solution to Ax=b:", solution)
print("Determinant:", determinant)
print("Inverse:\n", inverse)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("Vector norm:", norm)

## 10. Statistics for Data Science

These methods help summarize distributions and understand data spread.

In [ ]:
data = rng.normal(loc=70, scale=12, size=1000)

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))
print("25th, 50th, 75th percentiles:", np.percentile(data, [25, 50, 75]))
print("Correlation matrix:\n", np.corrcoef(data[:100], data[100:200]))

## 11. Unique Values and Counts

`unique()` is useful for understanding categories, duplicates, and frequency distributions.

In [ ]:
categories = np.array(["A", "B", "A", "C", "B", "A", "C", "C"])
unique_values, counts = np.unique(categories, return_counts=True)

print("Unique values:", unique_values)
print("Counts:", counts)
print("Frequency table:", dict(zip(unique_values, counts)))

## 12. Set Operations

Set operations help compare arrays, especially IDs, labels, and category values.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7])

print("Union:", np.union1d(a, b))
print("Intersection:", np.intersect1d(a, b))
print("In a but not b:", np.setdiff1d(a, b))
print("Values in both arrays mask:", np.isin(a, b))

## 13. Sorting 2D Arrays

Use `argsort()` when you need sorted indexes, such as sorting rows by a specific column.

In [ ]:
records = np.array([
    [101, 85],
    [102, 70],
    [103, 95],
    [104, 60]
])

sorted_by_score = records[np.argsort(records[:, 1])]
sorted_desc = records[np.argsort(records[:, 1])[::-1]]

print("Sorted ascending by score:\n", sorted_by_score)
print("Sorted descending by score:\n", sorted_desc)

## 14. Advanced Indexing with `take` and `put`

`take()` reads values by position. `put()` updates values by flat indexes.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
selected = np.take(arr, [0, 3, 4])

updated = arr.copy()
np.put(updated, [1, 3], [999, 777])

print("Selected:", selected)
print("Updated:", updated)

## 15. Universal Functions

Universal functions, or ufuncs, apply fast element-wise operations.

In [ ]:
values = np.array([1, 2, 3, 4, 5], dtype=float)

print("exp:", np.exp(values))
print("log:", np.log(values))
print("sin:", np.sin(values))
print("round:", np.round(np.sqrt(values), 2))

## 16. File Input and Output

NumPy can save and load arrays using binary `.npy` files or text-based `.csv` files.

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)

np.save("sample_array.npy", arr)
loaded = np.load("sample_array.npy")

np.savetxt("sample_array.csv", arr, delimiter=",", fmt="%d")
loaded_csv = np.loadtxt("sample_array.csv", delimiter=",")

print("Loaded from npy:\n", loaded)
print("Loaded from csv:\n", loaded_csv)

## 17. Performance: Vectorization vs Loops

In industry code, prefer vectorized NumPy operations for numerical work because they are shorter and usually faster.

In [ ]:
arr = np.arange(1, 1_000_001)

vectorized_result = arr * 2 + 5
loop_result = []
for value in arr[:10]:
    loop_result.append(value * 2 + 5)

print("First 10 vectorized results:", vectorized_result[:10])
print("First 10 loop results:", loop_result)

## 18. Mini Project: Clean and Analyze Sales Data

This small example combines filtering, missing value handling, aggregation, and feature creation.

In [ ]:
sales = np.array([
    [101, 250.0, 2],
    [102, np.nan, 1],
    [103, 500.0, 4],
    [104, 100.0, 0],
    [105, 750.0, 5]
])

customer_ids = sales[:, 0].astype(int)
amounts = sales[:, 1]
ratings = sales[:, 2]

clean_amounts = np.nan_to_num(amounts, nan=np.nanmean(amounts))
high_value_customers = customer_ids[clean_amounts >= 500]
average_sale = clean_amounts.mean()
positive_rating_mask = ratings > 0

print("Customer IDs:", customer_ids)
print("Clean amounts:", clean_amounts)
print("Average sale:", average_sale)
print("High value customers:", high_value_customers)
print("Customers with positive ratings:", customer_ids[positive_rating_mask])

## 19. Professional NumPy Checklist

- Use `np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, and `np.full` for array creation.
- Inspect arrays with `shape`, `ndim`, `size`, `dtype`, and `nbytes`.
- Prefer vectorized operations over loops.
- Use boolean masks for filtering.
- Understand views vs copies before modifying sliced data.
- Use broadcasting carefully and verify shapes.
- Use `np.linalg` for matrix and linear algebra operations.
- Use `np.nan_to_num`, `np.isnan`, and `np.isfinite` for messy numerical data.