# Operations On Arrays

In [2]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing",arr[2:7])
print("Basic slicing",arr[1:8:2])
print("Basic slicing",arr[-3:8])




Basic slicing [3 4 5 6 7]
Basic slicing [2 4 6 8]
Basic slicing [7 8]


In [10]:
arr_02 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("specific element", arr_02[1,2])
print("entire row",arr_02[2])
print("Entire column",arr_02[:,0])

specific element 6
entire row [7 8 9]
Entire column [1 4 7]


# Sorting

In [16]:
unsorted = np.array([3,1,4,2,8,1,6,4,6])
print("Sorted array",np.sort(unsorted))

arr_2d = np.array([
    [3,1],[1,2],[2,3]
])
print("Orginal array: ", arr_2d)
print("sorted array of 2D is: ", np.sort(arr_2d,axis = 0))
print("sorted array of 2D is: ", np.sort(arr_2d,axis = 1))


Sorted array [1 1 2 3 4 4 6 6 8]
Orginal array:  [[3 1]
 [1 2]
 [2 3]]
sorted array of 2D is:  [[1 1]
 [2 2]
 [3 3]]
sorted array of 2D is:  [[1 3]
 [1 2]
 [2 3]]


# Filter


In [18]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2 == 0]
print("The even numbers are: ",even_numbers)


The even numbers are:  [ 2  4  6  8 10]


# Filtering with Mask

In [19]:
mask = numbers>5
print("The numbers greater than 5 are: ",numbers[mask])

The numbers greater than 5 are:  [ 6  7  8  9 10]


# Fancy indexing vs np.where()

In [20]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print("NP where",numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [12]:
a= np.array([1,2,3,4,5])
a.shape

a2 = a[:,np.newaxis]
a2.shape

print(a.ndim)
print(a)
print(a2)
print(a2.shape)
np.nonzero(a2)

1
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


(array([0, 1, 2, 3, 4]), array([0, 0, 0, 0, 0]))

In [32]:
x= np.arange(1,25).reshape(2,12)
x
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [35]:
a = np.arange(2,10)
b = np.arange(10,18)
print("Concatenated array: ", np.concatenate((a,b)))
a+b


Concatenated array:  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


array([12, 14, 16, 18, 20, 22, 24, 26])

In [45]:
a = np.random.randint(2,10,(3,3))
a

array([[6, 7, 6],
       [4, 4, 9],
       [9, 2, 9]], dtype=int32)